version: "3.0"

services: 
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    volumes:
      - ./conf/custom.ini:/etc/grafana/grafana.ini
      # - grafana_volume:/var/lib/grafana
      - ./storage:/var/lib/grafana
    ports:
      - 3000:3000
    container_name: pragama_grafana
    

# volumes:
#   grafana_volume:
