version: "3.0"

services: 
  chronograf:
    image: chronograf:${CHRONOGRAF_VERSION}
    volumes:
      - ./chronograf/storage:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://127.0.0.1:8086
      KAPACITOR_URL: http://127.0.0.1:9093
      PORT: 8889
    ports:
      - 8889:8889
    container_name: pragama_chronograf_2
    network_mode: "host"
    
